server:
  port: 8080

logging:
  level:
    org.springframework: debug

spring:
  message:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"
